app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /site.com/admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /site.com/admin

_home:
    path: /site.com
    defaults: { _controller: AppBundle:MainPage:index }

category_name:
    path: /site.com/{slug}
    defaults: { _controller: AppBundle:CategoryPage:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
