AppBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        items:
            targetEntity: Goods
            inversedBy: category
            joinTable:
                name: category_goods
                joinColumns:
                    category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    goods_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
